services:
  backend:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
